services:
  - type: web
    name: trpc-websockets
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /api/trpc/healthcheck

databases:
  - name: trpc-websockets-db
    plan: free
